# This workflow will do a clean install of node dependencies, build the source code on Node 10 and 12, and format via Prettier

name: Node.js CI

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 12
              uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: npm install --global prettier
            - name: lint
              run: npm run format --write
            - name: Commit files
              run: |
                  git config --local user.email "linter@fractalcomputers.com"
                  git config --local user.name "fractal linter"
                  git diff-index --quiet HEAD || git commit -m "Linted with prettier" -a
