# This workflow will do a clean install of node dependencies and build the source code on Node 10 and 12
# It also runs jest tests

name: Node.js CI

on:
  pull_request:
    branches: [ master, staging ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 10.x, 12.x ]

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
              
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
  
      - name: Run yarn -i
        run: yarn -i
      
      - name: Install Jest Globally
        run: yarn global add jest # so the cli will work and you can just run "jest"

      - name: Run the tests
        run: yarn test a # a specifies all tests
