# This workflow will do a clean install of node dependencies and build the source code on Node 10 and 12

name: Node.js CI

on:
    pull_request:
        branches: [ master, staging ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [ 10.x, 12.x ]

        steps:
            - uses: actions/checkout@v2
              
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
  
            - name: Run npm ci
              run: npm ci
          
            - name: Run npm build
              run: npm run build --if-present
